//#define VIAL_UNLOCK_COMBO_ROWS {0,0}
//#define VIAL_UNLOCK_COMBO_COLS {0,12}
#define VIAL_KEYBOARD_UID {0xF1, 0x24, 0xA9, 0x5B, 0x21, 0xDF, 0xA8, 0x52}
#define VIAL_ENCODER_DEFAULT {KC_VOLD, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
#define VIAL_ENCODER_KEYCODE_DELAY 10
#undef ENCODER_DIRECTION_FLIP

